version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # - ../..:/workspaces:cached
      - type: bind
        source: ../
        target: /workspaces/repo
        consistency: cached
      - type: volume
        source: root-data
        target: /workspaces/repo/node_modules
      - type: volume
        source: frontend-data
        target: /workspaces/repo/packages/frontend/node_modules
      - type: volume
        source: backend-data
        target: /workspaces/repo/packages/backend/node_modules

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: main
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
  root-data:
  frontend-data:
  backend-data:
