name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: graphql codegen
        run: pnpm turbo codegen

      - name: typecheck
        run: pnpm turbo typecheck

      # - name: build
      #   run: pnpm turbo build

      # - name: eslint
      #   run: pnpm lint

      # - name: prettier
      #   run: pnpm format
